name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  load-tag:
    runs-on: ubuntu-latest
    name: Load tags
    outputs:
      tags: ${{ steps.list-tags.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Check tags
        id: list-tags
        run: |
          for i in "a b c"
          do
            versions+=("$i")
          done
          echo "tags={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT

  push-tag:
    runs-on: ubuntu-latest
    needs: [load-tag]
    strategy:
      matrix: ${{ fromJSON(needs.load-tag.outputs.tags) }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Push tag
        if: steps.checkTag.outputs.exists == 'false'
        run: |
          echo ${{ matrix.tag }}
