name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  load-tag:
    runs-on: ubuntu-latest
    name: Load tags
    outputs:
      tags: ${{ steps.list-tags.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Check tags
        id: list-tags
        run: |
          echo "tags={\"include\":[{\"version\":\"a\"},{\"version\":"\"b\"},{\"version\":\"c\"}]}" >> $GITHUB_OUTPUT

  push-tag:
    runs-on: ubuntu-latest
    needs: [load-tag]
    strategy:
      matrix: ${{ fromJSON(needs.load-tag.outputs.tags) }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Push tag
        run: |
          echo ${{ matrix.version }}
